server:
  # 端口
  port: 8080
  servlet:
    # 访问路径
    context-path: /
spring:
  application:
    # 应用名称
    name: GreenMallWeb
  datasource:
    # 数据库连接配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/greenmall
    username: root
    password: 245683yzf
  mybatis:
    # mybatis 别名配置
    type-aliases-package: com.yzf.greenmall.entity
  data:
    # elasticsearch 配置
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.230.128:9300
  jackson:
    # 配置json处理时忽略空值
    default-property-inclusion: non_null
  # redis
  redis:
    host: 192.168.230.128
  # rabbitmq
  rabbitmq:
    host: 192.168.230.128
    username: leorab
    password: 123456
    virtual-host: /greenmall
    # 生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试
    publisher-confirms: true
  thymeleaf:
    cache: false
# FastDFS 相关配置
fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 192.168.230.128:22122
greenmall:
  # 阿里短信配置
  sms:
    accessKeyId: LTAI4GEmhY1PVqubX4zcr9bB # 你自己的accessKeyId
    accessKeySecret: KridDZSnk4hqXtvNeduiRKzTWMJ21D # 你自己的AccessKeySecret
    signName: 绿色商城 # 签名名称
    verifyCodeTemplate: SMS_205615945 # 模板名称
  # 加密配置
  jwt:
    secret: greenmall@Login(Auth}*^31)&GM% # 登录校验的密钥
    pubKeyPath: D:/test/greenmall/rsa/rsa.pub # 公钥地址
    priKeyPath: D:/test/greenmall/rsa/rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: GM_TOKEN
    cookieMaxAge: 30
  # 登录拦截配置
  filter:
    filterPaths:
      - /user/hello
      - /user/queryUser
      - /shopCart
      - /collect
      - /address
  # 登录拦截用户信息加载配置
  interceptor:
    interceptorPaths:
      - /user/queryUser/
      - /shopCart/**
      - /collect/**
      - /address/**
