server:
  # 端口
  port: 8888
  servlet:
    # 访问路径
    context-path: /
spring:
  application:
    # 应用名称
    name: GreenMallAdmin
  datasource:
    # 数据库连接配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/greenmall
    username: root
    password: 245683yzf
  mybatis:
    # mybatis 别名配置
    type-aliases-package: com.yzf.greenmall.entity
  jackson:
    # 配置json处理时忽略空值
    default-property-inclusion: non_null
# FastDFS 相关配置
fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 192.168.230.128:22122
# 日志配置
logging:
  level:
    root: info
